# Site settings
title: SMPP REST API
email: chris@krslynx.com
description: > # this means to ignore newlines until "baseurl:"
  i love puzzles, i love code. i love problems. i love to solve. 
  i hate hubris. i hate rules. i hate it when people can't write their own tools.
baseurl: "/smpp-rest-api" # the subpath of your site, e.g. /blog/
url: "http://krslynx.com" # the base hostname & protocol for your site
twitter_username: krslynx
github_username:  krslynx
instagram_username: krslynx
facebook_username:  krslynx
stackex_username:	users/332597/krslynx
spotify_username:	user/krslynx

# Build settings
markdown: kramdown
